baseurl = "/"
title = "LiteCli"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "SQLite CLI with auto-completion and syntax highlighting"
  #copyright = "&copy;2016 Your name or company"
  sidebarAbout = ["SQLite Client w Auto-completion"]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "home/"
  home = true

  [[params.navlinks]]
  name = "Getting Started"
  url = "getting-started/"

  [[params.navlinks]]
  name = "Features"
  url = "features/"

  [[params.navlinks]]
  name = "News"
  url = "news/"

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  github        = "https://github.com/dbcli/litecli"
